In [1]:
import numpy as np

In [5]:
x = np.array([[0., 1.],
              [2., 3.],
              [4., 5.]])

print(x, x.shape)

[[0. 1.]
 [2. 3.]
 [4. 5.]] (3, 2)


In [6]:
x = x.reshape((6, 1))  # 重塑成 6*1
print(x, x.shape)

[[0.]
 [1.]
 [2.]
 [3.]
 [4.]
 [5.]] (6, 1)


In [7]:
x = x.reshape((2, 3))
print(x, x.shape)

[[0. 1. 2.]
 [3. 4. 5.]] (2, 3)


In [8]:
# 矩陣轉置

x = np.zeros((300, 100))
print("轉置前: ", x.shape)

x = np.transpose(x)
 print("轉置後: ", x.shape)

轉置前:  (300, 100)
轉置後:  (100, 300)
