In [1]:
import numpy as np

In [2]:
# 建立一個 2D 張量
arr = np.zeros((2, 4)) # 建立一個 shape 為 (2, 4) 的全  0 張量
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [3]:
# 看 shape
arr.shape

(2, 4)

In [4]:
# 看型別
arr.dtype

dtype('float64')

In [5]:
# 花式操作陣列

arr[0, [1,3]] = 1.  # 把第 0 列的 1, 3 變 1
arr

array([[0., 1., 0., 1.],
       [0., 0., 0., 0.]])

In [13]:
# 產生隨機值的陣列，範圍在 0~1之間。 
layer_mask = np.random.randint(0, high=2, size=(5, 5))
layer_mask

array([[1, 1, 1, 0, 0],
       [1, 1, 0, 0, 1],
       [1, 1, 0, 1, 1],
       [1, 0, 1, 1, 0],
       [0, 1, 1, 0, 1]])