In [1]:
#!pip install tensorflow-gpu==2.0.0

In [2]:
import tensorflow as tf

In [3]:
#tf.__version__

In [4]:
# 這理介紹一下   tf.linalg.band_part()  使用方法。

# tf.linalg.band_part() 主要功能以對角線為中心，取它的副對角線部分，其他部分用0填充，甚麼意思呢?
# 簡單話來說，就是把一個矩陣右上三角變 0 或左下三角變 0 

In [5]:
# 先看一下 API

"""tf.linalg.band_part  
  Args:
    input: 輸入的陣列
    num_lower: 下三角矩陣保留的副對角線數量，從主對角線開始計算，相當於下三角的帶寬。取值爲負數時，則全部保留，矩陣不變。
    num_upper: 上三角矩陣保留的副對角線數量，從主對角線開始計算，相當於上三角的帶寬。取值爲負數時，則全部保留，矩陣不變。
    name=None: 不重要

  Returns:
    matrix
"""

'tf.linalg.band_part  \n  Args:\n    input: 輸入的陣列\n    num_lower: 下三角矩陣保留的副對角線數量，從主對角線開始計算，相當於下三角的帶寬。取值爲負數時，則全部保留，矩陣不變。\n    num_upper: 上三角矩陣保留的副對角線數量，從主對角線開始計算，相當於上三角的帶寬。取值爲負數時，則全部保留，矩陣不變。\n    name=None: 不重要\n\n  Returns:\n    matrix\n'

In [6]:
# 或許看了 API 之後還是不懂，那直接看實作:

matrix_a = tf.ones([4, 4], tf.int32)
print("matrix_a = ", matrix_a)

matrix_b = tf.linalg.band_part(matrix_a, 0, 0)
print("matrix_b = ", matrix_b)

matrix_c = tf.linalg.band_part(matrix_a, 1, 0)
print("matrix_c = ", matrix_c)

matrix_d = tf.linalg.band_part(matrix_a, 2, 0)
print("matrix_d = ", matrix_d)

matrix_e = tf.linalg.band_part(matrix_a, 3, 0)
print("matrix_e = ", matrix_e)

matrix_a =  tf.Tensor(
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]], shape=(4, 4), dtype=int32)
matrix_b =  tf.Tensor(
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]], shape=(4, 4), dtype=int32)
matrix_c =  tf.Tensor(
[[1 0 0 0]
 [1 1 0 0]
 [0 1 1 0]
 [0 0 1 1]], shape=(4, 4), dtype=int32)
matrix_d =  tf.Tensor(
[[1 0 0 0]
 [1 1 0 0]
 [1 1 1 0]
 [0 1 1 1]], shape=(4, 4), dtype=int32)
matrix_e =  tf.Tensor(
[[1 0 0 0]
 [1 1 0 0]
 [1 1 1 0]
 [1 1 1 1]], shape=(4, 4), dtype=int32)


In [7]:
# 這樣一看是不是馬上明朗很多了?接下來試試看 num_lower 參數調 -1

matrix_f = tf.linalg.band_part(matrix_a, -1, 0)
print("matrix_f = ", matrix_f)

matrix_f =  tf.Tensor(
[[1 0 0 0]
 [1 1 0 0]
 [1 1 1 0]
 [1 1 1 1]], shape=(4, 4), dtype=int32)


In [8]:
# 可以看到，我們把 num_lower 調成 -1 之後就等於下方三角全部保留，如果想保留上方三角呢?

matrix_g = tf.linalg.band_part(matrix_a, 0, -1)
print("matrix_g = ", matrix_g)

matrix_g =  tf.Tensor(
[[1 1 1 1]
 [0 1 1 1]
 [0 0 1 1]
 [0 0 0 1]], shape=(4, 4), dtype=int32)
