In [1]:
import numpy as np

In [2]:
x = np.array([[0., 1.],
              [2., 3.],
              [4., 5.]])

print(x, x.shape)

[[0. 1.]
 [2. 3.]
 [4. 5.]] (3, 2)


In [3]:
x = x.reshape((6, 1))  # 重塑成 6*1
print(x, x.shape)

[[0.]
 [1.]
 [2.]
 [3.]
 [4.]
 [5.]] (6, 1)


In [4]:
x = x.reshape((2, 3))
print(x, x.shape)

[[0. 1. 2.]
 [3. 4. 5.]] (2, 3)


In [6]:
# 矩陣轉置

x = np.zeros((300, 100))
print("轉置前: ", x.shape)

x = np.transpose(x)
print("轉置後: ", x.shape)

轉置前:  (300, 100)
轉置後:  (100, 300)


In [17]:
# 難一點的

x = np.ones((2, 10, 4))
x

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [19]:
# 把原本的最後一個 4 維變 2 維，變完之後因為要想以 (10, 2) 這種 shape 為一組，所以在 10 前面加 -1。
x = np.reshape(x, newshape=(2, -1, 10, 2))
x

array([[[[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]]]])

In [20]:
x = x.transpose((0, 2, 1, 3))
x

array([[[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]]])